### ISSUE TITLE
Emoji Size

### ISSUE THREAD

**Issue by comepso** [sylvaindurand/emojione-phpbb#1]
even with the emoji size set to 20x20 when you actually post a emoji they display to their full size. please provide instruction on how to modify styles to display them smaller

**Comment by comepso** [comment]
Disregard above comment, i found the solution. You need search for the following code in message_parser.php
` $replace[] = '<img src="{SMILIES_PATH}/' . $row['smiley_url'] . '" alt="' . $row['code'] . '" title="' . $row['emotion'] . '" />';
`
and replace with
```
			/*
                old smiley code does not resize
                $replace[] = '<!-- s' . $row['code'] . ' --><img src="{SMILIES_PATH}/' . $row['smiley_url'] . '" alt="' . $row['code'] . '" title="' . $row['emotion'] . '" /><!-- s' . $row['code'] . ' -->';*/
                
                //new smiliy resize code based on each smiley w x h setting
                $replace[] = '<!-- s' . $row['code'] . ' --><img src="{SMILIES_PATH}/' . $row['smiley_url'] . '" alt="' . $row['code'] . '" title="' . $row['emotion'] . '" width="' . $row['smiley_width'] . '" height="' . $row['smiley_height'] .'" /><!-- s' . $row['code'] . ' -->';
```

**Comment by sylvaindurand** [comment]
Yes! It is also possible to style them (as I did) with CSS.
