### ISSUE TITLE
Ajax error

### ISSUE THREAD

**Issue by 8BiTw0LF** [sylvaindurand/emojione-phpbb#2]
After installing the emojis I get this message in the ACP: `Fatal: Not able to open ./../cache/data_global.php`

When trying to purge i get this: 
![screenshot 1 png](https://cloud.githubusercontent.com/assets/20681312/19618926/7c0539da-9858-11e6-85be-2d52134f9da0.png)
`AJAX error. status: parsererror, message: SyntaxError: JSON.parse: unexpected non-whitespace character after JSON data at line 1 column 1086 of the JSON datacore.js:262:5`

**Comment by 8BiTw0LF** [comment]
Solved. Only needed to delete my cache manually.

**Comment by sylvaindurand** [comment]
I'm glad it works ;)
