### ISSUE TITLE
emoji very big on subject or chat

### ISSUE THREAD

**Issue by CristiOprea** [sylvaindurand/emojione-phpbb#3]
Every emoji wich i select, is very big on page, is not resize...please solved it.

**Comment by sylvaindurand** [comment]
Just a CSS in your template will do!
I'll try to see what I can do ;)

**Comment by xPrcek** [comment]
Big emoji is (template) CSS issue, this works: /styles/<stylename>/theme/common.css

```
.emoji, .smilies {
     min-height: 18px;
     min-width: 18px;
     height: 1em;
     width: 1em;
}
```
